# -*- coding: utf-8 -*-
"""OPENAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15n6P1RblyzHqIiIWi0P_W2jqC52-DmC4
"""

!pip install openpyxl

# Import packages
import glob
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/gdrive')

df = pd.read_excel('/content/gdrive/MyDrive/DATASET TITLE.xlsx', engine='openpyxl')

df

"""INSTALL OPENAI"""

!pip install openai

import os
import openai

openai.api_key = "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"

"""TRY THE MESSAGE'S TRANSLATION"""

response = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "I want you to act as this is a message from a taiwan university, please translate formally from chinese to english, only TRANSLATE it, do not give me any other words except for the translation. The message is:"},
        {"role": "user", "content": "112年暑期iHouse學生會館區住宿申請提醒 國合處已於5/26公告112年暑期iHouse學生會館區住宿申請"}
     ]
  )

response['choices'][0]['message']["content"]

sentiments = []
sentiments

for i in range(0, 50):

    print(i)

    message = df['TITLE'][i]

    response = openai.ChatCompletion.create(
      model="gpt-3.5-turbo",
      messages=[
        {"role": "system", "content": "I want you to act as this is a message from a taiwan university, please translate formally from chinese to english, only TRANSLATE it, do not give me any other words except for the translation. The message is:"},
        {"role": "user", "content": message}
         ]
    )

    sentiment = response['choices'][0]['message']["content"]
    sentiments.append([i, sentiment])
    #sentiments.append(sentiment)

    #time.sleep(3)

#Print the current value of i on each iteration
print(i)

#Ensure the length of sentiments
len(sentiments)

sentiments

sentiment_df = pd.DataFrame(sentiments, columns=['order', 'openAI TITLE translation'])

sentiment_df

#Save OpenAI's response first
sentiment_df.to_excel('//content/gdrive/MyDrive/labelled.xlsx', index=False)

"""Merge the result to the Data File (DF)"""

df_merged = pd.concat([df, sentiment_df], axis=1)

df_merged